// src/components/custom-sites/index.tsx
import {
    component$,
    useStore,
    useStyles$,
    $,
    useBrowserVisibleTask$,
} from "@builder.io/qwik";
import Modal from "~/components/modal";
import CardSite from "~/routes/card-mode/CardSite";
import style from "./index.scss?inline";

interface ILocalSite {
    name: string;
    link: string;
    desc: string;
}

// QWIK WARN Serializing dirty watch. Looks like an internal error.
// it seems like a qwik internal bug
// https://github.com/BuilderIO/qwik/issues/2715
export default component$(() => {
    useStyles$(style);

    const store = useStore({
        modalTitle: "新增私人收藏站点",
        modalOkText: "确定",
        modalCancelText: "取消",
        modalVisible: false,
        name: "",
        link: "",
        desc: "",
        localList: [] as ILocalSite[],
    });

    useBrowserVisibleTask$(() => {
        const item = window.localStorage.getItem("__local_sites__");
        store.localList = item ? JSON.parse(item) : ([] as ILocalSite[]);
    });

    useBrowserVisibleTask$(({ track }) => {
        track(() => store.localList);

        localStorage.setItem("__local_sites__", JSON.stringify(store.localList));
    });

    const resetTempSite = $(() => {
        store.name = "";
        store.desc = "";
        store.link = "";
    });

    const handleOk = $(() => {
        if (store.name && store.link && store.desc) {
            store.localList = [
                ...store.localList,
                {
                    name: store.name,
                    link: store.link,
                    desc: store.desc,
                },
            ];
            resetTempSite();
            store.modalVisible = false;
        }
    });

    const handleCancel = $(() => {
        resetTempSite();
        store.modalVisible = false;
    });

    return (
        <>
            <div
                class="btn cursor-pointer m-5px dark:bg-#eee dark:text-black"
                onClick$={() => (store.modalVisible = true)}
            >
                新增私人收藏站点 👏
            </div>
            {store.localList.length > 0 && (
                <section>
                    <div class="mb-10px dark:text-white text-[30px]">
                        <div class="i-mdi-file-table-outline text-orange-400" />
                        <span class="relative top-3px">私人收藏</span>
                    </div>
                    <div class="item-wrapper">
                        {store.localList.map((site, index) => (
                            <div class="item-wrapper">
                                <CardSite site={site} key={index} />
                            </div>
                        ))}
                    </div>
                </section>
            )}
            <Modal
                visible={store.modalVisible}
                title={store.modalTitle}
                okText={store.modalOkText}
                cancelText={store.modalCancelText}
                onCancel={handleCancel}
                onOk={handleOk}
            >
                <div class="flex flex-col">
                    <input
                        type="text"
                        placeholder="请输入需要添加的站点名称"
                        class="m-2 p-2 border-none bg-[#f1f1f1] b-rd"
                        onInput$={(ev) =>
                            (store.name = (ev.target as HTMLInputElement).value)
                        }
                    />
                    <input
                        type="text"
                        placeholder="请输入需要添加的站点url"
                        class="m-2 p-2 border-none bg-[#f1f1f1] b-rd"
                        onInput$={(ev) =>
                            (store.link = (ev.target as HTMLInputElement).value)
                        }
                    />
                    <textarea
                        cols={30}
                        rows={10}
                        placeholder="请输入站点描述信息"
                        class="m-2 p-2 border-none bg-[#f1f1f1] b-rd resize-none"
                        onInput$={(ev) =>
                            (store.desc = (ev.target as HTMLInputElement).value)
                        }
                    />
                </div>
            </Modal>
        </>
    );
});

// src/routes/home/CustomSites.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import FormModal from "./FormModal.svelte";
  import SimpleButton from "@/components/SimpleButton.svelte";

  let modalVisible = false;
  let newSite = {} // 新增站点

  interface ILocalSite {
    name: string;
    link: string;
  }

  let localList = [];
  onMount(() => {
    const item = localStorage.getItem("__local_sites__");
    if (item) {
      localList = JSON.parse(item);
    }
  })


  $: {
    if (localList.length) {
      localStorage.setItem("__local_sites__", JSON.stringify(localList));
    }

    // 关闭弹窗时 删除已填数据
    if (!modalVisible) {
      newSite = {}
    }
  }

  const handleOk = () => {
    console.log('111: ', newSite)
    if (newSite.name && newSite.link) {
      localList = [
        ...localList,
        {...newSite},
      ] as ILocalSite[]
    }
    modalVisible = false
  };

  const handleCancel = () => {
    modalVisible = false
  };

</script>

<div>
    <section class="mt-15px">
      <div class="mb-10px text-26px">
        <div class="i-mdi-file-table-outline text-orange-400"></div>
        <span class="relative top-3px">私人收藏</span>
      </div>
      <div class="item-wrapper inline-block">
        {#each localList as site}
          <SimpleButton>
            <a href="{site.link}" target="_blank" class="bg-black text-white">
              { site.name }
            </a>
          </SimpleButton>
        {/each}
      </div>
      <div
          class="btn cursor-pointer m-5px inline-block"
          on:click={() => (modalVisible = true)}
      >
        新增私人收藏站点 👏
      </div>
    </section>

  <FormModal
      visible={modalVisible}
      title={'新增私人收藏站点'}
      onCancel={handleCancel}
      onOk={handleOk}
  >
    <div class="flex flex-col">
      <input
          type="text"
          placeholder="请输入需要添加的站点名称"
          class="m-2 p-2 border-none bg-[#f1f1f1] b-rd"
          on:input={(ev) =>
                            (newSite.name = (ev.target).value)
                        }
      />
      <input
          type="text"
          placeholder="请输入需要添加的站点url"
          class="m-2 p-2 border-none bg-[#f1f1f1] b-rd"
          on:input={(ev) =>
                            (newSite.link = (ev.target).value)
                        }
      />
    </div>
  </FormModal>
</div>

<style lang="scss">
  .btn {
    width: fit-content;
    padding: 7px 15px;
    background: #000028;
    border-radius: 20px;
    color: white;
  }

  .btn:hover {
    box-shadow: 4px 4px 8px gray;
  }

</style>
