// src/routes/list-mode/List.tsx
import { component$, useStore } from "@builder.io/qwik";
import { allSites } from "~/utils/sites";
import OneSite from "./OneSite";
import CategoryTitle from "~/components/CategoryTitle";

export default component$(() => {
  const store = useStore({
    allSites
  });

  return (
    <section class='all-sites'>
      { store.allSites.map((list, index) => {
        return <div class='site-block my-30px' key={index}>
          <CategoryTitle category={list}></CategoryTitle>
          {list.sites.map((site: any, secIndex) => {
            return <OneSite site={site} key={secIndex}></OneSite>
          })}
        </div>
      })}
    </section>
  )
})

// src/routes/home/List.svelte
<script lang="ts">
  import { allSites } from "@/utils/sites";
  import Card from "./Card.svelte";
  import CategoryTitle from "./CategoryTitle.svelte";

</script>

<section class="all-sites">
  {#each allSites as list}
    <div class="site-block my-30px">
      <CategoryTitle category={list} />
      <div class="item-wrapper">
        {#each list.sites as site}
          <Card site={site} />
        {/each}
      </div>
    </div>
  {/each}
</section>

<style lang="scss">
  .item-wrapper {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
    gap: 24px;
  }
</style>
