// src/routes/card-mode/List.tsx
import { component$, useStyles$, useStore } from "@builder.io/qwik";
import { allSites } from "~/utils/sites";
import CardSite from "./CardSite";
import CategoryTitle from "~/components/CategoryTitle";
import ListStyle from "./List.css?inline";

export default component$(() => {
	useStyles$(ListStyle);
	const store = useStore({
		allSites,
	});

	return (
		<section class="all-sites">
			{store.allSites.map((list, index) => {
				return (
					<div class="site-block my-30px" key={index}>
						<CategoryTitle category={list} />
						<div class="item-wrapper">
							{list.sites.map((site, secIndex) => (
								<CardSite site={site} key={secIndex} />
							))}
						</div>
					</div>
				);
			})}
		</section>
	);
});

// src/components/pageList/List.svelte
<script lang="ts">
  import Card from "./Card.svelte";
  import CategoryTitle from "./CategoryTitle.svelte";

  export let pageSites = [];
</script>

<section class="all-sites space-y-36px mt-24px">
  {#each pageSites as list}
    <div class="site-block">
      <CategoryTitle category={list} />
      <div class="item-wrapper">
        {#each list.sites as site}
          <Card site={site} />
        {/each}
      </div>
    </div>
  {/each}
</section>

<style lang="scss">
  .item-wrapper {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
    gap: 24px;
  }
</style>
